# Generated by Django 4.2.16 on 2024-10-17 16:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0002_alter_movie_actors_alter_movie_release_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comentários')),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'O mínimo de estrelas é 0'), django.core.validators.MaxValueValidator(5, 'O máximo de estrelas é 5')], verbose_name='Estrelas')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='movies.movie', verbose_name='Filme')),
            ],
        ),
    ]
