# Generated by Django 4.2.16 on 2024-10-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0003_alter_actor_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='actor',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='nationality',
            field=models.CharField(blank=True, choices=[('USA', 'Estados Unidos'), ('BRA', 'Brasil')], max_length=100, null=True, verbose_name='Nacionalidade'),
        ),
    ]
